### ISSUE TITLE
Urban Dictionary (theme: Speak Easy) - Campaign

### ISSUE THREAD

**Issue by ghost** [humanetech-community/awareness-program#22]
# [Campaign name here] Urban Dictionary

## Info 

- Name: **Urban Dictionary**
- Theme: [Speak Easy](https://github.com/humanetech-community/humanetech-community-awareness/issues/19)
- General discussion: [Forum topic title here](forum-topic-url)

## Summary 

The Speak Easy initiative calls for introducing new terms and expressions to the common language. Since we will probably not be able to dedicate a campaign to each of the new terms we come up with (instead focusing on those with the highest viral potential), the idea is here to consolidate all proposed terms into a dedicated dictionary, which we could spread and regularly update. 

## Goals

- Promote widespread adoption of new language terms designed to improve bad tech habits

- Create, share, and maintain a dedicated dictionary of new language terms

## Audience

- All ages (therefore need to be mindful of crude terms) (Note: teenagers nowadays are usually the first to catch on new expressions and share them with adults)

## Success criteria

- Number of hits of a webpage where we would maintain the dictionary

## Retrospective

- No retrospective has been held yet. The first retrospective is planned at [retrospective date].

## Description

It is proposed to create and maintain a dictionary, where new entries would be proposed by the community (since we do not dedicate much time to spreading each specific term, the need to filter would be less). Reminder: all terms should be related to bad habits associated with technology.

Entries should look like those in a typical dictionary, giving it an authentic feel. They should deliberately be worded in a funny, and catchy way.

Examples of such entries would be as follows:

**Phone Zombie (noun, pejorative)**

1. Someone who is so engrossed with his phone at most times that he seems neither dead or alive.

2. Someone who irritates his friends in a social setting by constantly looking at his phone.

Example: "Patrick, don't be such a bloody phone zombie. You have not said a word since you got here"

**Google slut (expression, pejorative)**

1. Someone who whores his most intimate thoughts to Google in exchange for free information on the most embarrassing topics.

Example: "So, last night I was searching online for stories from people faced with the same situation, and..." Tom, you are such a Google slut. Why don't you talk to your friends instead?"

## Deliverables

First draft to be elaborated on this thread. Once ready, a webpage where it would be hosted and maintained.

## Strategy

- This campaign does not require a strategy. Strategy is defined on the Theme, or in Deliverables.

## Funding

- No funding is required to execute this campaign. 

## Resources

- This theme has no additional resources. Please edit or comment to add your relevant links.

**Comment by georgeshk** [comment]
Discussions on new words and expressions should come here. So far, we have three:

- Phone zombie
- Google slut
- Phubbing (https://en.m.wikipedia.org/wiki/Phubbing)

**Comment by patmatsu** [comment]
>Promote widespread adoption of new language terms designed to improve bad tech habits

Don't you mean "correct bad tech habits"?

**Comment by georgeshk** [comment]
> Don't you mean "correct bad tech habits"?

Yes indeed. Thanks

**Comment by aschrijver** [comment]
While your proposal could very well be used, I want to make the case for a common strategy at the Theme level, followed by individual Campaigns per language term / meme. Let me explain.

This theme is primarily about language & memes, and ensuring that each new term / meme is adopted. Which means that each campaign is long-running and requires separate monitoring and steering, and variations of strategy on top of the common Theme strategy. Each campaign also has series of Deliverables on a single language term, that will be created over time, with different use cases.

With your proposal Speak Easy theme has the same meaning as Urban Dictionary campaign, and the theme will probably only ever contain a single campaign.

An example that demonstrates my proposal:

- Theme: **Speak Easy** / Urban Dictionary (common strategy --> how do we spread language/memes over the internet, using social media and other sources)

  - Campaign: **Phone Zombies** (strategy --> common strategy + extra attention to specific social media channels e.g. moblie, WhatsApp, etc.)

    - Deliverables:
      - Video's (YouTube, Vimeo, PeerTube, social sharing, etc.)
      - Images (Article headers, link previews, social sharing, etc.)
      - Animated GIF's (WhatsApp, Snapchat, social sharing, etc.)
      - T-shirts & coffee cups, etc.

  - Campaign: **Tech Vader** (strategy --> common strategy + completely different target audience: IT techies on the workfloor)

    - Deliverables:
      - Screensavers (_"Thou shalt not enter, Tech Vader!"_)
      - Wall posters (_"Luke.. Fight the Evil Forces! - Ethics matter"_, etc.)
      - Office gadgets (Big red button with Tech Vader icon: _"Evil alert! We are under attack.. Man your posts!"_)

So with this structure you avoid having an enormous amount of deliverables in one campaign on different terms, and a strategy with many paragraphs "If you working on this meme, use this strategy, otherwise use ...").

**Comment by georgeshk** [comment]
@aschriver:

I read your comment above a few times, I feel I understand what you mean (i.e. one campaign dedicated to each selected expression, all under Speak Easy, which includes a number of possible deliverables).

The idea suggested in this issue is to recycle all the proposed expressions that do not make it to dedicated campaigns into a "urban dictionary" dedicated to negative tech aspects. Maybe I should not call it a campaign, since it is in effect quite simple. I did not mean to distract from the original purposes of the Speak Easy theme (though this idea here naturally falls under that theme).

**Comment by aschrijver** [comment]
Maybe the Urban Dictionary is maintained in the `/strategy` section of the project, and indeed not a campaign?

**Comment by aschrijver** [comment]
The Urban Dictionary could also be published on a website section (e.g. `urbandictionary.humanetech.community` and be a continuous reference for the community, but also the wider public). In that case it has a concrete Campaign ongoing, where the website is promoted.

**Comment by georgeshk** [comment]
>  In that case it has a concrete Campaign ongoing, where the website is promoted.

My thinking exactly. First we would populate with definitions as per the sample format above, then promote it. I will clarify the idea in the original description.

**Comment by aschrijver** [comment]
Agreed. This also means we'll move all the definitions from the other campaigns to record them in one central, public place. Great! The deliverable of Urban Dictionary is a website (or subdomain section thereof).

**Comment by georgeshk** [comment]
Just revised my post on the Theme issue. Discussions in this Campaign issue would be limited to logistics on how to build and advertise the dictionary. Sorry for the mess

**Comment by aschrijver** [comment]
No problem at all. This issue proposal now needs a slight overhaul to reflect the new insights.

**Comment by patmatsu** [comment]
You two know about this crowdsourced project?

https://www.urbandictionary.com/

**Comment by healthyswimmer** [comment]
“Road blocker” or “barricade” when blocking corridors or doorways staring at phone.  

Not in urban dictionary but I just experienced this at a swim meet..  pardon my emotions here but annoying and rude.

**Comment by aschrijver** [comment]
Good one! I have adde 'Road Blocker' to 'Speak Easy' theme document in the 'Candidates section.
